[build]
publish = "public"
command = """\
  npm install sass-embedded-linux-x64@${DART_SASS_VERSION} && \
  mkdir -p /opt/build/repo/node_modules/.bin && \
  cp -r /opt/build/repo/node_modules/sass-embedded-linux-x64/dart-sass-embedded/* /opt/build/repo/node_modules/.bin/ && \
  dart-sass-embedded --version && \
  hugo --gc --minify \
  """

[build.environment]
HUGO_VERSION = "0.140.0"
DART_SASS_VERSION = "1.86.0"