backend:
  name: git-gateway
  branch: master # Branch to update (optional; defaults to master)
display_url: https://sportclimbs.uk
site_url: https://sportclimbs.uk
media_folder: "static/img/uploads" # Media files will be stored in the repo under static/images/uploads
public_folder: "/img/uploads" # The src attribute for uploaded media will begin with /images/uploads
publish_mode: editorial_workflow
collections:
- name: "peak"
  label: "Peak District"
  folder: "peak"
  create: true
  editor:
    preview: true
  fields:
  - {label: "Page Title", name: "title", widget: "string"}
  - {label: "Link Title (only needed if the main title is long", name: "linktitle", widget: "string"}
  - {label: "Subtitle (used if a crag has a second name)", name: "subtitle", widget: "string"}